[package]
name = "fazasanj-scan"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
fazasanj-model = { workspace = true }
fazasanj-platform = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
log = { workspace = true }
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher", "inline-more"] }

[dev-dependencies]
tempfile = { workspace = true }
