[package]
name = "fazasanj-heuristics"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
fazasanj-model = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
blake3 = "1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile = { workspace = true }
